export enum MODELS {
  O4_MINI = "o4-mini",
  O3_MINI = "o3-mini",
  GPT_4_1 = "gpt-4.1",
  GPT_4_1_MINI = "gpt-4.1-mini",
  GPT_5 = "gpt-5",
  GPT_5_MINI = "gpt-5-mini",

  GPT_5_NANO = "gpt-5-nano",

  GPT_4o = "gpt-4o",
  GEMINI_1_5_FLASH = "gemini-1.5-flash",
  GEMINI_2_0_FLASH = "gemini-2.0-flash",
  GEMINI_2_5_FLASH = "gemini-2.5-flash",
  GEMINI_2_5_PRO = "gemini-2.5-pro",
  GEMINI_2_0_FLASH_LITE = "gemini-2.0-flash-lite",
  GEMINI_2_5_FLASH_LITE = "gemini-2.5-flash-lite-preview-06-17",
  GEMINI_3_FLASH = "gemini-3-flash-preview",

  GEMINI_2_0_PRO = "gemini-2.0-pro-exp-02-05",
  DEEPSEEK_LLAMA_8B = "deepseek/deepseek-r1-distill-llama-8b",
  DEEPSEEK_QWEN_2_5_SMALL = "deepseek/deepseek-r1-distill-qwen-1.5b",
  DEEPSEEK_QWEN_2_5_MEDIUM = "deepseek/deepseek-r1-distill-qwen-14b",
  DEEPSEEK_QWEN_2_5_LARGE = "deepseek/deepseek-r1-distill-qwen-32b",
  LLAMA_3_2_11B_VISION_INSTRUCT = "meta-llama/llama-3.2-11b-vision-instruct",
  LLAMA_3_2_90B_VISION_INSTRUCT = "meta-llama/llama-3.2-90b-vision-instruct",
  CLAUDE_3_5_SONNET = "anthropic/claude-3.5-sonnet",
  CLAUDE_4_SONNET = "anthropic/claude-sonnet-4",
  GLM_4_5 = "glz-ai/glm-4.5",
  DEEPSEEK_V3 = "deepseek/deepseek-chat-v3-0324",
  DEEPSEEK_R1_0528 = "deepseek/deepseek-r1-0528",
  KIMI_K2 = "moonshotai/kimi-k2",
  GROK_4 = "x-ai/grok-4",
  GROK_3_MINI = "x-ai/grok-3-mini",
  MAGISTRAL_MEDIUM_2506 = "mistralai/magistral-medium-2506",
  MAGISTRAL_MEDIUM_2506_THINKING = "mistralai/magistral-medium-2506:thinking",
  MAGISTRAL_SMALL_2506 = "mistralai/magistral-small-2506",
  PERPLEXITY_SONAR = "sonar",
  OPENAI_GPT_OSS_20B = "openai/gpt-oss-20b",
  OPENAI_GPT_OSS_120B = "openai/gpt-oss-120b",
  SONOMA_DUSK_ALPHA = "openrouter/sonoma-dusk-alpha",
  SONOMA_SKY_ALPHA = "openrouter/sonoma-sky-alpha",
  QWEN_3_NEXT_80B_A3B_THINKING = "qwen/qwen3-next-80b-a3b-thinking",
  GROK_CODE_FAST_1 = "x-ai/grok-code-fast-1",
  GROK_4_1_FAST = "x-ai/grok-4.1-fast",
}
